[package]
name = "dsmr-influxdb-adapter"
version = "0.1.0"
authors = ["Robin Bolscher <robinbolscher@gmail.com>"]
edition = "2018"

[dependencies]
mio = "0.6"
mio-serial = "3.3"
tokio = { version = "0.2.22", features = ["full"] }
reqwest = "0.10"
chrono = "0.4.19"